"""
NLI Confidence Calibration Script
===================================
Measures actual NLI confidence distributions against the 119-claim benchmark
dataset and fits per-status calibration bounds.

Output: hallucination_middleware/nli_calibration.json
This file is loaded by Verifier._calibrate_confidence() to replace the static
_CONF_BOUNDS defaults with empirically measured parameters.

Usage:
    python scripts/calibrate_nli.py

Requirements:
    - Pipeline must be importable (run from project root)
    - sentence-transformers must be installed (always true if running the server)
    - Takes ~30 s on GPU, ~3 min on CPU

Re-run whenever:
    - The NLI model changes (small ↔ large)
    - New benchmark claims are added to evaluation.py
    - Observed confidence distributions shift significantly
"""
import json
import logging
import sys
from pathlib import Path

# Allow running from project root without installing the package
sys.path.insert(0, str(Path(__file__).parent.parent))

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger("calibrate_nli")

OUTPUT_PATH = Path("hallucination_middleware/nli_calibration.json")


def _get_evidence(claim_text: str, is_true: bool) -> str:
    """
    Construct a synthetic evidence sentence for calibration.
    For TRUE claims: use the claim itself (perfect entailment — upper bound).
    For FALSE claims: use a negation (perfect contradiction — lower bound).
    This measures the model's output range, not real retrieval recall.
    """
    if is_true:
        return claim_text  # Self-entailment: should score 0.85–1.00 entailment
    # Simple negation: prepend "It is false that"
    return f"It is false that {claim_text[0].lower()}{claim_text[1:]}"


def run_calibration():
    from hallucination_middleware.nli_scorer import get_nli_scorer
    from hallucination_middleware.evaluation import (
        BENCHMARK_CLAIMS,
        MEDICAL_BENCHMARK_CLAIMS,
        LEGAL_BENCHMARK_CLAIMS,
        FINANCIAL_BENCHMARK_CLAIMS,
    )

    nli = get_nli_scorer()
    all_claims = (
        BENCHMARK_CLAIMS
        + MEDICAL_BENCHMARK_CLAIMS
        + LEGAL_BENCHMARK_CLAIMS
        + FINANCIAL_BENCHMARK_CLAIMS
    )
    logger.info("Running NLI calibration on %d benchmark claims …", len(all_claims))

    # Collect (raw_conf, expected_status) pairs per status bucket
    buckets: dict = {
        "verified": [],
        "contradicted": [],
        "partially_supported": [],
        "unverifiable": [],
    }

    for bc in all_claims:
        evidence = _get_evidence(bc.text, bc.ground_truth)
        conf, status = nli.score_pair(bc.text, evidence)
        expected = "verified" if bc.ground_truth else "contradicted"
        buckets[status].append((conf, expected))

    logger.info("Status distribution from NLI:")
    for s, items in buckets.items():
        logger.info("  %-22s %3d samples", s, len(items))

    # Fit per-status calibration bounds from observed distributions
    calibration: dict = {}
    for status, items in buckets.items():
        if not items:
            continue
        confs = [c for c, _ in items]
        lo = max(0.05, min(confs) - 0.02)   # 2% below observed minimum
        hi = min(0.99, max(confs) + 0.02)   # 2% above observed maximum
        mean = sum(confs) / len(confs)
        calibration[status] = {
            "lo": round(lo, 3),
            "hi": round(hi, 3),
            "mean": round(mean, 3),
            "n": len(items),
        }
        logger.info(
            "  %-22s lo=%.3f  hi=%.3f  mean=%.3f  (n=%d)",
            status, lo, hi, mean, len(items),
        )

    # Sanity check: contradicted lo must be above block_threshold (0.50)
    # so that confident contradictions trigger BLOCK in the decision engine
    if "contradicted" in calibration and calibration["contradicted"]["lo"] < 0.50:
        old_lo = calibration["contradicted"]["lo"]
        calibration["contradicted"]["lo"] = 0.65
        logger.warning(
            "contradicted lo=%.3f is below block_threshold=0.50 — "
            "clamped to 0.65 to ensure contradictions trigger BLOCK",
            old_lo,
        )

    calibration["_meta"] = {
        "source": "benchmark_calibration",
        "total_claims": len(all_claims),
        "note": "Generated by scripts/calibrate_nli.py — re-run after model changes",
    }

    OUTPUT_PATH.write_text(json.dumps(calibration, indent=2))
    logger.info("Calibration saved → %s", OUTPUT_PATH)
    return calibration


if __name__ == "__main__":
    run_calibration()
